name: 'Setup Innersource Actions'

inputs:  
  GH_PAT_TOKEN:
    required: true
  INNER_SOURCE_ACTIONS_APP_ID:
    required: true
  INNER_SOURCE_ACTIONS_APP_PRIVATE_KEY_BASE64:
    required: true
runs:
  using: "composite"
  steps:
    # Setup inner source actions
    - name: Get Token
      id: token
      uses: philips-software/app-token-action@v1.0.2
      with:
        app_id: ${{ inputs.INNER_SOURCE_ACTIONS_APP_ID }}
        app_base64_private_key: ${{ inputs.INNER_SOURCE_ACTIONS_APP_PRIVATE_KEY_BASE64 }}
        auth_type: "installation"

    - uses: philips-software/inner-source-checkout-action@v1.1.0
      with:
        token: ${{ steps.token.outputs.token }}
        base_dir: ../.actions
        repos: philips-internal/terragrunt-plan-action@v1, philips-internal/terragrunt-apply-action@v1

    - uses: actions/checkout@v2

    - uses: philips-labs/terraform-private-modules-action@v1.1
      with:
        org: philips-internal
        token: ${{ inputs.GH_PAT_TOKEN }}