name: Deploy HDS Auth Gateway with a given Oauth2 Proxy Image Tag

on:   
  workflow_call:
    inputs:
      OAUTH2_PROXY_IMAGE:
        type: string
        required: true
    secrets:
      VAULT_HOST:
        required: true
      VAULT_ROLE_ID:
        required: true
      VAULT_SECRET_ID:
        required: true

jobs:
  Deploy_HDS_Auth_Gateway_With_Token_Authenticator_Image:
    runs-on: ubuntu-20.04 
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: ${{ secrets.VAULT_HOST }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: true
          secrets: |
            devops/data/github/users/sal-devops token | GITHUB_TOKEN ;
            
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: philips-internal
          repo: hds-auth-gateway
          github_token: ${{ env.GITHUB_TOKEN }}
          client_payload: '{"oauth2proxytag": "${{ inputs.OAUTH2_PROXY_IMAGE }}"}'
          workflow_file_name: ci.yaml
          ref: master