name: 'Terragrunt Output'

inputs:  
  working-directory:
    description: "Working directory - path to your Terragrunt module"
    required: true
  key:
    description: "Key used to save plan file to artifacts"
    required: true

runs:
  using: "composite"
  steps:    
    - id: terragrunt_output
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terragrunt output -json > /tmp/output.json        
    
    - name: Upload Output
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.key }}
        path: /tmp/output.json
        if-no-files-found: error